"""
Taxonomie joburi RO/EN pentru motorul NEXAS HR.
Scop: clasificare stabila pe familii profesionale, nu scor AI liber.

Structura:
- 30 familii mari
- fiecare familie are aliasuri RO/EN
- fiecare familie are minim 10 subfamilii

Nu contine date personale. Poate fi extinsa fara sa modifici promptul AI.
"""

JOB_TAXONOMY = {
    "IT_SOFTWARE": {
        "label": "IT Software",
        "aliases": ["software", "developer", "programator", "dezvoltator", "programare", "coding", "cod", "aplicatii", "web", "frontend", "backend", "full stack", "fullstack", "mobile developer", "java", "python", "javascript", "typescript", "react", "angular", "node", "php", "c#", ".net"],
        "subfamilies": {
            "backend_development": ["backend", "back-end", "api", "server", "java", "python", "node", "php", ".net", "c#", "spring", "django", "fastapi", "laravel"],
            "frontend_development": ["frontend", "front-end", "react", "angular", "vue", "html", "css", "javascript", "typescript", "ui developer"],
            "fullstack_development": ["full stack", "fullstack", "mern", "mean", "web developer", "dezvoltator web"],
            "mobile_development": ["mobile", "android", "ios", "flutter", "react native", "swift", "kotlin"],
            "qa_automation": ["qa automation", "test automation", "selenium", "cypress", "playwright", "automation tester"],
            "embedded_software": ["embedded", "firmware", "c", "c++", "microcontroller", "iot"],
            "game_development": ["game developer", "unity", "unreal", "game programming"],
            "database_development": ["sql developer", "pl/sql", "database developer", "stored procedures"],
            "software_architecture": ["software architect", "arhitect software", "solution architect"],
            "low_code_development": ["low code", "power apps", "oracle apex", "outsystems"],
        },
        "must_have_any": ["programator", "developer", "software", "cod", "programare", "frontend", "backend", "fullstack", "java", "python", "javascript", "typescript", "react", "angular", "node", "php", "c#", ".net", "sql", "git"],
    },
    "IT_INFRASTRUCTURE": {
        "label": "IT Infrastructure",
        "aliases": ["system administrator", "sysadmin", "administrator sistem", "network", "retelistica", "devops", "cloud", "server", "linux", "windows server", "infrastructure"],
        "subfamilies": {
            "system_administration": ["system administrator", "sysadmin", "administrator sistem", "server", "windows server", "linux"],
            "network_engineering": ["network engineer", "retelistica", "ccna", "routing", "switching", "firewall"],
            "devops": ["devops", "ci/cd", "docker", "kubernetes", "terraform", "jenkins"],
            "cloud_engineering": ["cloud", "aws", "azure", "gcp", "cloud engineer"],
            "database_administration": ["dba", "database administrator", "sql server", "oracle dba", "mysql"],
            "it_operations": ["it operations", "noc", "monitoring", "incident management"],
            "virtualization": ["vmware", "hyper-v", "virtualizare"],
            "storage_backup": ["backup", "storage", "veeam", "nas", "san"],
            "middleware": ["middleware", "application server", "tomcat", "jboss"],
            "site_reliability": ["sre", "site reliability", "observability", "prometheus", "grafana"],
        },
        "must_have_any": ["server", "linux", "windows server", "network", "retelistica", "devops", "cloud", "aws", "azure", "docker", "kubernetes", "firewall", "ccna"],
    },
    "IT_SUPPORT": {
        "label": "IT Support",
        "aliases": ["it support", "helpdesk", "service desk", "suport tehnic", "technical support", "desktop support", "support engineer"],
        "subfamilies": {
            "helpdesk": ["helpdesk", "help desk", "service desk", "ticketing"],
            "desktop_support": ["desktop support", "pc support", "windows", "office 365"],
            "field_it_support": ["field support", "onsite support", "interventii it"],
            "technical_support": ["technical support", "suport tehnic"],
            "application_support": ["application support", "suport aplicatii"],
            "hardware_support": ["hardware", "laptop", "pc", "printer", "imprimanta"],
            "it_asset_management": ["asset management", "inventar it", "licente"],
            "service_delivery": ["service delivery", "sla", "itil"],
            "telecom_support": ["telecom", "voip", "telefonie"],
            "junior_it": ["junior it", "intern it", "entry level it"],
        },
        "must_have_any": ["it support", "helpdesk", "service desk", "suport tehnic", "ticket", "hardware", "windows", "office 365", "printer", "pc"],
    },
    "DATA_BI": {
        "label": "Data & BI",
        "aliases": ["data analyst", "analist date", "bi", "business intelligence", "data engineer", "reporting", "power bi", "tableau", "sql", "excel avansat"],
        "subfamilies": {
            "data_analysis": ["data analyst", "analist date", "analiza date"],
            "business_intelligence": ["bi", "business intelligence", "power bi", "tableau", "looker"],
            "data_engineering": ["data engineer", "etl", "pipeline", "spark", "airflow"],
            "reporting": ["reporting", "raportare", "dashboard"],
            "analytics_engineering": ["dbt", "analytics engineer"],
            "data_science": ["data scientist", "machine learning", "ml", "python data"],
            "database_reporting": ["sql", "query", "baze de date"],
            "excel_analysis": ["excel avansat", "pivot", "power query"],
            "crm_analytics": ["crm analytics", "salesforce reports"],
            "operations_analytics": ["operations analyst", "analist operational"],
        },
        "must_have_any": ["data", "analist date", "bi", "power bi", "tableau", "sql", "reporting", "excel", "dashboard", "etl"],
    },
    "CYBERSECURITY": {
        "label": "Cybersecurity",
        "aliases": ["cybersecurity", "securitate cibernetica", "security analyst", "soc", "pentest", "information security", "infosec"],
        "subfamilies": {
            "soc": ["soc", "security operations", "siem"],
            "security_analysis": ["security analyst", "analist securitate"],
            "penetration_testing": ["pentest", "penetration tester", "ethical hacker"],
            "governance_risk_compliance": ["grc", "iso 27001", "risk", "compliance"],
            "identity_access": ["iam", "identity", "access management"],
            "network_security": ["network security", "firewall", "ids", "ips"],
            "cloud_security": ["cloud security", "aws security", "azure security"],
            "application_security": ["application security", "appsec", "secure coding"],
            "incident_response": ["incident response", "forensics"],
            "security_engineering": ["security engineer", "securitate it"],
        },
        "must_have_any": ["security", "cyber", "securitate", "soc", "siem", "pentest", "iso 27001", "firewall"],
    },
    "FINANCE_ACCOUNTING": {
        "label": "Finance & Accounting",
        "aliases": ["contabil", "accountant", "accounting", "financiar", "financial", "economist", "facturi", "bilant", "taxe", "fiscal", "raportare financiara"],
        "subfamilies": {
            "accounting": ["contabil", "accountant", "contabilitate"],
            "financial_analysis": ["financial analyst", "analist financiar"],
            "payables": ["accounts payable", "ap", "furnizori"],
            "receivables": ["accounts receivable", "ar", "clienti"],
            "payroll": ["payroll", "salarizare"],
            "tax": ["tax", "fiscal", "declaratii fiscale"],
            "audit": ["audit", "auditor"],
            "controlling": ["controller", "controlling"],
            "treasury": ["treasury", "cash management"],
            "bookkeeping": ["bookkeeping", "evidenta contabila", "saga"],
        },
        "must_have_any": ["contabil", "contabilitate", "accounting", "accountant", "financiar", "economist", "fiscal", "facturi", "bilant", "saga"],
    },
    "BANKING_INSURANCE": {
        "label": "Banking & Insurance",
        "aliases": ["banking", "banca", "credit", "asigurari", "insurance", "broker", "daune", "claims", "underwriting"],
        "subfamilies": {
            "retail_banking": ["retail banking", "consilier bancar"],
            "corporate_banking": ["corporate banking", "business banking"],
            "credit_analysis": ["credit analyst", "analist credit"],
            "insurance_sales": ["broker asigurari", "agent asigurari"],
            "claims": ["daune", "claims"],
            "underwriting": ["underwriter", "subscriere"],
            "risk_banking": ["risk banking", "risc bancar"],
            "payments": ["payments", "plati"],
            "leasing": ["leasing"],
            "kyc_aml": ["kyc", "aml", "compliance bancar"],
        },
        "must_have_any": ["banca", "banking", "credit", "asigurari", "insurance", "broker", "daune", "underwriting", "kyc", "aml"],
    },
    "HR_RECRUITMENT": {
        "label": "HR & Recruitment",
        "aliases": ["hr", "human resources", "resurse umane", "recruiter", "recrutare", "talent acquisition", "personal", "training"],
        "subfamilies": {
            "recruitment": ["recruiter", "recrutare", "talent acquisition"],
            "hr_generalist": ["hr generalist", "generalist resurse umane"],
            "payroll_hr": ["salarizare", "payroll hr", "revisal"],
            "hr_admin": ["administrare personal", "contracte munca"],
            "learning_development": ["learning", "training", "l&d"],
            "employer_branding": ["employer branding"],
            "compensation_benefits": ["compensation", "benefits", "c&b"],
            "hr_business_partner": ["hr business partner", "hrbp"],
            "organizational_development": ["organizational development", "dezvoltare organizationala"],
            "employee_relations": ["employee relations", "relatii angajati"],
        },
        "must_have_any": ["hr", "resurse umane", "recruiter", "recrutare", "talent acquisition", "revisal", "salarizare", "training"],
    },
    "LEGAL": {
        "label": "Legal",
        "aliases": ["jurist", "legal", "lawyer", "avocat", "consilier juridic", "contracte", "litigii", "compliance legal"],
        "subfamilies": {
            "legal_advisor": ["jurist", "consilier juridic", "legal advisor"],
            "lawyer": ["avocat", "lawyer", "attorney"],
            "contracts": ["contracte", "contracts"],
            "litigation": ["litigii", "litigation"],
            "corporate_law": ["corporate law", "drept societar"],
            "labor_law": ["dreptul muncii", "labor law"],
            "gdpr_privacy": ["gdpr", "privacy", "protectia datelor"],
            "legal_compliance": ["legal compliance", "conformitate juridica"],
            "public_procurement_legal": ["achizitii publice", "seap"],
            "paralegal": ["paralegal", "asistent juridic"],
        },
        "must_have_any": ["jurist", "legal", "avocat", "drept", "contracte", "litigii", "gdpr", "consilier juridic"],
    },
    "MARKETING": {
        "label": "Marketing",
        "aliases": ["marketing", "brand", "communication", "comunicare", "campaign", "campanii", "content", "copywriting", "pr"],
        "subfamilies": {
            "brand_marketing": ["brand", "brand manager"],
            "marketing_generalist": ["marketing specialist", "marketing coordinator"],
            "content_marketing": ["content", "copywriting", "blog", "newsletter"],
            "communications": ["comunicare", "communication", "corporate communication"],
            "public_relations": ["pr", "public relations", "relatii publice"],
            "event_marketing": ["event marketing", "evenimente"],
            "trade_marketing": ["trade marketing"],
            "product_marketing": ["product marketing"],
            "market_research": ["market research", "cercetare piata"],
            "marketing_management": ["marketing manager", "head of marketing"],
        },
        "must_have_any": ["marketing", "brand", "campanii", "communication", "comunicare", "content", "copywriting", "pr"],
    },
    "DIGITAL_MARKETING": {
        "label": "Digital Marketing",
        "aliases": ["digital marketing", "seo", "ppc", "google ads", "facebook ads", "meta ads", "social media", "performance marketing", "email marketing", "ecommerce marketing"],
        "subfamilies": {
            "seo": ["seo", "search engine optimization"],
            "ppc": ["ppc", "google ads", "paid search"],
            "social_media": ["social media", "facebook", "instagram", "tiktok", "linkedin"],
            "performance_marketing": ["performance marketing", "paid media"],
            "email_marketing": ["email marketing", "newsletter", "mailchimp"],
            "ecommerce_marketing": ["ecommerce", "shopify", "woocommerce"],
            "marketing_automation": ["marketing automation", "hubspot", "marketo"],
            "analytics_digital": ["google analytics", "ga4", "tag manager"],
            "affiliate_marketing": ["affiliate", "afiliere"],
            "growth_marketing": ["growth", "growth marketing"],
        },
        "must_have_any": ["digital marketing", "seo", "ppc", "google ads", "facebook ads", "social media", "performance", "email marketing", "ga4"],
    },
    "SALES_B2B": {
        "label": "Sales B2B",
        "aliases": ["sales", "vanzari", "agent vanzari", "account manager", "key account", "business development", "b2b", "consultant vanzari"],
        "subfamilies": {
            "account_management": ["account manager", "gestiune clienti"],
            "key_account": ["key account", "kam"],
            "business_development": ["business development", "bdm"],
            "field_sales": ["field sales", "agent teren"],
            "inside_sales": ["inside sales", "telesales b2b"],
            "technical_sales": ["technical sales", "inginer vanzari"],
            "sales_representative": ["sales representative", "reprezentant vanzari"],
            "sales_management": ["sales manager", "director vanzari"],
            "crm_sales": ["crm", "pipeline", "salesforce"],
            "channel_sales": ["channel sales", "distribuitori"],
        },
        "must_have_any": ["vanzari", "sales", "account manager", "key account", "business development", "clienti", "crm", "ofertare"],
    },
    "SALES_RETAIL": {
        "label": "Sales Retail",
        "aliases": ["lucrator comercial", "vanzator", "sales assistant", "retail", "magazin", "casier", "cashier", "shop assistant", "merchandiser"],
        "subfamilies": {
            "cashier": ["casier", "cashier", "casa de marcat", "pos", "incasari"],
            "shop_assistant": ["vanzator", "lucrator comercial", "sales assistant"],
            "store_management": ["sef magazin", "store manager"],
            "merchandising": ["merchandiser", "aranjare marfa"],
            "fashion_retail": ["fashion retail", "haine", "incaltaminte"],
            "grocery_retail": ["supermarket", "hypermarket", "alimentar"],
            "electronics_retail": ["electronice", "electrocasnice"],
            "pharmacy_retail": ["farmacie retail", "consultant farmacie"],
            "beauty_retail": ["beauty advisor", "cosmetice"],
            "retail_stock": ["receptioner marfa magazin", "stoc magazin"],
        },
        "must_have_any": ["casier", "cashier", "retail", "magazin", "lucrator comercial", "vanzator", "casa de marcat", "pos", "incasari"],
    },
    "CUSTOMER_SUPPORT": {
        "label": "Customer Support",
        "aliases": ["customer support", "suport clienti", "call center", "operator call center", "customer care", "client service", "contact center"],
        "subfamilies": {
            "call_center": ["call center", "contact center", "operator telefonic"],
            "customer_care": ["customer care", "relatii clienti"],
            "technical_customer_support": ["technical support clienti", "suport tehnic clienti"],
            "chat_support": ["chat support", "live chat"],
            "email_support": ["email support", "ticketing clienti"],
            "bpo_support": ["bpo", "outsourcing suport"],
            "complaints": ["reclamatii", "complaints"],
            "retention": ["retention", "fidelizare"],
            "multilingual_support": ["multilingual support", "limbi straine"],
            "back_office_support": ["back office support", "procesare cereri"],
        },
        "must_have_any": ["customer support", "suport clienti", "call center", "customer care", "relatii clienti", "telefonic", "ticketing"],
    },
    "ADMINISTRATIVE": {
        "label": "Administrative",
        "aliases": ["administrativ", "secretara", "asistent manager", "office assistant", "office manager", "receptie birou", "data entry", "operator introducere date"],
        "subfamilies": {
            "office_assistant": ["office assistant", "asistent birou"],
            "secretarial": ["secretara", "secretariat"],
            "executive_assistant": ["executive assistant", "asistent manager"],
            "office_management": ["office manager", "administrare birou"],
            "data_entry": ["data entry", "operator introducere date", "validare date"],
            "document_control": ["document control", "arhivare"],
            "reception_office": ["receptie birou", "front desk"],
            "administrative_support": ["administrative support", "suport administrativ"],
            "fleet_admin": ["fleet admin", "administrare flota"],
            "facilities_admin": ["facilities admin", "administrare facilitati"],
        },
        "must_have_any": ["administrativ", "secretara", "office", "asistent manager", "data entry", "introducere date", "arhivare", "receptie"],
    },
    "PROCUREMENT_PURCHASING": {
        "label": "Procurement & Purchasing",
        "aliases": ["achizitii", "procurement", "purchasing", "buyer", "cumparari", "sourcing", "furnizori", "licitatii"],
        "subfamilies": {
            "buyer": ["buyer", "cumparator"],
            "procurement_specialist": ["procurement specialist", "specialist achizitii"],
            "strategic_sourcing": ["sourcing", "strategic sourcing"],
            "supplier_management": ["supplier management", "management furnizori"],
            "public_procurement": ["achizitii publice", "seap", "licitatii"],
            "indirect_procurement": ["indirect procurement"],
            "direct_procurement": ["direct procurement", "materii prime"],
            "contract_procurement": ["contract procurement", "contracte furnizori"],
            "import_purchasing": ["import", "achizitii externe"],
            "procurement_analysis": ["procurement analyst", "analist achizitii"],
        },
        "must_have_any": ["achizitii", "procurement", "purchasing", "buyer", "furnizori", "sourcing", "licitatii"],
    },
    "SUPPLY_CHAIN": {
        "label": "Supply Chain",
        "aliases": ["supply chain", "planificare", "demand planning", "production planning", "inventory", "stocuri", "material planner"],
        "subfamilies": {
            "demand_planning": ["demand planner", "planificare cerere"],
            "supply_planning": ["supply planner", "planificare aprovizionare"],
            "production_planning": ["production planner", "planificare productie"],
            "inventory_management": ["inventory", "stocuri", "gestiune stocuri"],
            "material_planning": ["material planner", "mrp"],
            "s_and_op": ["s&op", "sales and operations planning"],
            "logistics_planning": ["logistics planning", "planificare logistica"],
            "order_management": ["order management", "gestionare comenzi"],
            "supply_chain_analysis": ["supply chain analyst", "analist supply"],
            "import_export": ["import export", "export", "vama"],
        },
        "must_have_any": ["supply chain", "planner", "planificare", "inventory", "stocuri", "mrp", "comenzi", "import", "export"],
    },
    "LOGISTICS_WAREHOUSE": {
        "label": "Logistics & Warehouse",
        "aliases": ["depozit", "warehouse", "manipulant", "manipulant marfa", "picker", "packer", "ambalare", "gestionar", "stivuitorist", "forklift", "receptie marfa", "inventar depozit"],
        "subfamilies": {
            "warehouse_worker": ["manipulant", "manipulant marfa", "warehouse worker", "incarcare", "descarcare"],
            "picking_packing": ["picker", "packer", "picking", "packing", "ambalare"],
            "warehouse_clerk": ["gestionar", "warehouse clerk", "gestiune depozit"],
            "forklift_operator": ["stivuitorist", "forklift", "motostivuitor", "iscir"],
            "goods_receiving": ["receptie marfa", "goods receiving"],
            "inventory_control": ["inventar", "inventory control"],
            "warehouse_supervisor": ["sef depozit", "warehouse supervisor"],
            "returns_processing": ["retururi", "returns"],
            "loading_unloading": ["incarcare", "descarcare", "rampa"],
            "warehouse_scan": ["scanner", "wms", "scanare"],
        },
        "must_have_any": ["depozit", "warehouse", "manipulant", "picker", "packer", "gestionar", "stivuitor", "forklift", "marfa", "wms", "iscir"],
    },
    "TRANSPORTATION": {
        "label": "Transportation",
        "aliases": ["sofer", "driver", "curier", "livrator", "transport", "distributie", "tir", "camion", "categoria b", "categoria c", "categoria ce"],
        "subfamilies": {
            "delivery_driver": ["sofer distributie", "delivery driver", "livrari", "categoria b"],
            "courier": ["curier", "courier"],
            "truck_driver": ["sofer camion", "categoria c", "truck driver"],
            "tir_driver": ["tir", "categoria ce", "international driver"],
            "bus_driver": ["sofer autobuz", "categoria d"],
            "taxi_rideshare": ["taxi", "rideshare", "uber", "bolt"],
            "dispatcher": ["dispecer transport", "dispatcher"],
            "fleet_driver": ["flota", "sofer companie"],
            "transport_coordinator": ["coordonator transport", "transport coordinator"],
            "special_transport": ["adr", "transport agabaritic", "frigorific"],
        },
        "must_have_any": ["sofer", "driver", "curier", "livrator", "transport", "distributie", "categoria b", "categoria c", "categoria ce", "tir"],
    },
    "PRODUCTION_MANUFACTURING": {
        "label": "Production & Manufacturing",
        "aliases": ["productie", "operator productie", "manufacturing", "fabrica", "linie productie", "asamblare", "operator cnc", "calitate productie"],
        "subfamilies": {
            "production_operator": ["operator productie", "linie productie", "fabrica"],
            "assembly": ["asamblare", "assembly"],
            "cnc_operator": ["cnc", "operator cnc"],
            "machine_operator": ["operator masina", "machine operator"],
            "quality_control": ["control calitate", "quality control", "qc"],
            "process_operator": ["operator proces", "process operator"],
            "packaging_production": ["ambalare productie", "packaging"],
            "textile_production": ["textile", "confectii"],
            "food_production": ["productie alimentara"],
            "production_supervisor": ["sef schimb", "production supervisor"],
        },
        "must_have_any": ["productie", "operator", "fabrica", "linie", "asamblare", "cnc", "calitate", "manufacturing"],
    },
    "MAINTENANCE_TECHNICAL": {
        "label": "Maintenance & Technical Service",
        "aliases": ["mentenanta", "maintenance", "tehnician mentenanta", "intretinere", "service tehnic", "reparatii echipamente", "electromecanic"],
        "subfamilies": {
            "industrial_maintenance": ["mentenanta industriala", "industrial maintenance"],
            "mechanical_maintenance": ["mentenanta mecanica", "mechanical maintenance"],
            "electrical_maintenance": ["mentenanta electrica", "electrical maintenance"],
            "electromechanical": ["electromecanic", "electromechanical"],
            "facility_maintenance": ["facility maintenance", "intretinere cladiri"],
            "equipment_service": ["service echipamente", "reparatii echipamente"],
            "preventive_maintenance": ["mentenanta preventiva"],
            "hvac_maintenance": ["hvac", "climatizare"],
            "automation_maintenance": ["automatizari", "plc maintenance"],
            "maintenance_supervisor": ["sef mentenanta", "maintenance supervisor"],
        },
        "must_have_any": ["mentenanta", "maintenance", "tehnician", "intretinere", "reparatii", "electromecanic", "service echipamente"],
    },
    "MECHANICAL_ENGINEERING": {
        "label": "Mechanical Engineering",
        "aliases": ["inginer mecanic", "mechanical engineer", "proiectare mecanica", "cad", "solidworks", "catia", "autocad", "design engineer"],
        "subfamilies": {
            "mechanical_design": ["proiectare mecanica", "mechanical design", "solidworks", "catia"],
            "cad_engineering": ["cad", "autocad", "inventor"],
            "process_engineering": ["process engineer", "inginer proces"],
            "manufacturing_engineering": ["manufacturing engineer", "inginer productie"],
            "quality_engineering": ["quality engineer", "inginer calitate"],
            "r_and_d_engineering": ["r&d", "research development"],
            "product_engineering": ["product engineer", "inginer produs"],
            "tooling_engineering": ["tooling", "matrite", "scule"],
            "industrial_engineering": ["industrial engineer", "inginer industrial"],
            "maintenance_engineering": ["maintenance engineer", "inginer mentenanta"],
        },
        "must_have_any": ["inginer mecanic", "mechanical engineer", "proiectare", "cad", "solidworks", "catia", "autocad", "inginer productie"],
    },
    "AUTOMOTIVE_SERVICE": {
        "label": "Automotive Service",
        "aliases": ["mecanic auto", "auto mechanic", "service auto", "atelier auto", "diagnoza auto", "frane", "suspensie", "distributii", "electrician auto", "tinichigiu", "vopsitor auto"],
        "subfamilies": {
            "auto_mechanic": ["mecanic auto", "auto mechanic", "service auto", "revizii", "frane", "suspensie", "distributii"],
            "assistant_mechanic": ["ajutor mecanic", "ucenic mecanic"],
            "auto_electrician": ["electrician auto", "auto electrician"],
            "diagnostic_technician": ["diagnoza auto", "tester diagnoza", "diagnostic technician"],
            "body_repair": ["tinichigiu", "tinichigerie", "body repair"],
            "auto_painter": ["vopsitor auto", "auto painter"],
            "ac_service": ["ac auto", "climatizare auto"],
            "tire_service": ["vulcanizare", "anvelope"],
            "itp": ["itp", "inspectie tehnica"],
            "service_advisor": ["consilier service", "receptie service auto"],
        },
        "must_have_any": ["mecanic auto", "service auto", "atelier auto", "diagnoza auto", "revizii", "frane", "suspensie", "distributii", "electrician auto", "tinichigiu", "vopsitor auto"],
    },
    "ELECTRICAL_ENGINEERING": {
        "label": "Electrical Engineering",
        "aliases": ["electrician", "inginer electric", "electrical", "instalatii electrice", "tablouri electrice", "automatizari", "plc"],
        "subfamilies": {
            "electrician": ["electrician", "instalatii electrice"],
            "electrical_engineer": ["inginer electric", "electrical engineer"],
            "automation_engineer": ["automation engineer", "automatizari", "plc"],
            "panel_builder": ["tablouri electrice", "panel builder"],
            "industrial_electrician": ["electrician industrial"],
            "maintenance_electrician": ["electrician mentenanta"],
            "low_voltage": ["curenti slabi", "low voltage"],
            "high_voltage": ["inalta tensiune", "high voltage"],
            "electrical_design": ["proiectare electrica", "eplan"],
            "testing_commissioning": ["testing commissioning", "punere in functiune"],
        },
        "must_have_any": ["electrician", "electric", "instalatii electrice", "tablouri", "automatizari", "plc", "eplan"],
    },
    "CONSTRUCTION": {
        "label": "Construction",
        "aliases": ["constructii", "constructor", "zidar", "dulgher", "fierar betonist", "instalator", "santier", "muncitor constructii", "inginer constructii"],
        "subfamilies": {
            "civil_engineering": ["inginer constructii", "civil engineer"],
            "site_management": ["sef santier", "site manager"],
            "mason": ["zidar", "mason"],
            "carpenter": ["dulgher", "carpenter"],
            "rebar_worker": ["fierar betonist"],
            "plumber": ["instalator", "plumber"],
            "welder": ["sudor", "welder"],
            "painter_construction": ["zugrav", "finisaje"],
            "quantity_surveyor": ["devizier", "quantity surveyor"],
            "machine_operator_construction": ["excavator", "buldoexcavator", "macaragiu"],
        },
        "must_have_any": ["constructii", "santier", "zidar", "dulgher", "instalator", "sudor", "fierar", "finisaje", "devizier"],
    },
    "HOSPITALITY": {
        "label": "Hospitality",
        "aliases": ["hotel", "receptioner hotel", "hospitality", "turism", "pensiune", "front office", "housekeeping", "cazare"],
        "subfamilies": {
            "hotel_reception": ["receptioner hotel", "front office", "receptie hotel"],
            "housekeeping": ["housekeeping", "camerista"],
            "hotel_management": ["hotel manager", "manager hotel"],
            "reservations": ["rezervari", "reservations"],
            "concierge": ["concierge"],
            "guest_relations": ["guest relations", "relatii oaspeti"],
            "tourism_agent": ["agent turism", "travel agent"],
            "spa_hospitality": ["spa", "wellness"],
            "event_hospitality": ["evenimente hotel", "banqueting"],
            "night_auditor": ["night auditor", "receptie noapte"],
        },
        "must_have_any": ["hotel", "receptioner", "hospitality", "turism", "pensiune", "front office", "housekeeping", "rezervari"],
    },
    "FOOD_SERVICE": {
        "label": "Food Service",
        "aliases": ["bucatar", "chef", "cook", "ospatar", "waiter", "server", "barman", "bartender", "restaurant", "horeca", "cafenea", "patiser", "cofetar"],
        "subfamilies": {
            "waiter": ["ospatar", "waiter", "server", "chelner", "servire clienti"],
            "cook": ["bucatar", "cook", "chef", "line cook"],
            "assistant_cook": ["ajutor bucatar", "kitchen helper"],
            "bartender": ["barman", "bartender", "bar"],
            "barista": ["barista", "cafea", "coffee"],
            "pastry": ["patiser", "patiserie", "pastry"],
            "confectionery": ["cofetar", "cofetarie"],
            "kitchen_management": ["chef bucatar", "sous chef", "chef de partie"],
            "fast_food": ["fast food", "lucrator fast food"],
            "catering": ["catering", "cantina"],
        },
        "must_have_any": ["bucatar", "chef", "cook", "ospatar", "waiter", "server", "barman", "restaurant", "horeca", "cafenea", "patiser", "cofetar"],
    },
    "HEALTHCARE": {
        "label": "Healthcare",
        "aliases": ["medical", "asistent medical", "medic", "nurse", "doctor", "clinica", "spital", "farmacist", "kinetoterapeut", "ingrijitor"],
        "subfamilies": {
            "nursing": ["asistent medical", "nurse", "generalist"],
            "doctor": ["medic", "doctor"],
            "pharmacy": ["farmacist", "pharmacist"],
            "physiotherapy": ["kinetoterapeut", "physiotherapist"],
            "dental": ["stomatologie", "asistent dentar"],
            "medical_reception": ["receptie clinica", "front desk medical"],
            "caregiver": ["ingrijitor", "caregiver"],
            "laboratory": ["laborator medical", "analize medicale"],
            "radiology": ["radiologie", "imagistica"],
            "healthcare_admin": ["administrativ medical", "spital"],
        },
        "must_have_any": ["medical", "asistent medical", "medic", "nurse", "doctor", "clinica", "spital", "farmacist", "kinetoterapeut"],
    },
    "EDUCATION": {
        "label": "Education",
        "aliases": ["profesor", "teacher", "educator", "trainer", "formator", "invatator", "lector", "instructor", "training"],
        "subfamilies": {
            "teacher": ["profesor", "teacher"],
            "primary_teacher": ["invatator", "primary teacher"],
            "kindergarten": ["educator", "gradinita"],
            "trainer": ["trainer", "formator"],
            "language_teacher": ["profesor limbi", "english teacher"],
            "university": ["lector", "universitar"],
            "instructional_design": ["instructional designer"],
            "school_admin": ["administrator scoala"],
            "tutor": ["meditator", "tutor"],
            "sports_instructor": ["instructor sport", "coach"],
        },
        "must_have_any": ["profesor", "teacher", "educator", "trainer", "formator", "invatator", "lector", "instructor"],
    },
    "MANAGEMENT_LEADERSHIP": {
        "label": "Management & Leadership",
        "aliases": ["manager", "director", "team lead", "coordonator", "supervisor", "head of", "operations manager", "project manager"],
        "subfamilies": {
            "project_management": ["project manager", "manager proiect", "pmp", "scrum master"],
            "operations_management": ["operations manager", "manager operational"],
            "team_leadership": ["team lead", "coordonator echipa"],
            "general_management": ["general manager", "director general"],
            "department_management": ["department manager", "sef departament"],
            "product_management": ["product manager", "product owner"],
            "program_management": ["program manager"],
            "plant_management": ["plant manager", "factory manager"],
            "service_management": ["service manager"],
            "business_management": ["business manager", "unit manager"],
        },
        "must_have_any": ["manager", "director", "team lead", "coordonator", "supervisor", "head of", "project manager", "operations manager"],
    },
}

# Familii care pot fi apropiate, dar nu egale.
# Folosit pentru scoruri near/transferable.
RELATED_FAMILIES = {
    "IT_SOFTWARE": {"DATA_BI", "IT_INFRASTRUCTURE", "IT_SUPPORT", "CYBERSECURITY"},
    "DATA_BI": {"IT_SOFTWARE", "FINANCE_ACCOUNTING", "SUPPLY_CHAIN"},
    "IT_SUPPORT": {"IT_INFRASTRUCTURE", "IT_SOFTWARE"},
    "IT_INFRASTRUCTURE": {"IT_SUPPORT", "CYBERSECURITY", "IT_SOFTWARE"},
    "CYBERSECURITY": {"IT_INFRASTRUCTURE", "IT_SOFTWARE"},
    "FINANCE_ACCOUNTING": {"BANKING_INSURANCE", "DATA_BI", "ADMINISTRATIVE"},
    "BANKING_INSURANCE": {"FINANCE_ACCOUNTING", "SALES_B2B", "CUSTOMER_SUPPORT"},
    "HR_RECRUITMENT": {"ADMINISTRATIVE", "MANAGEMENT_LEADERSHIP"},
    "LEGAL": {"ADMINISTRATIVE", "BANKING_INSURANCE"},
    "MARKETING": {"DIGITAL_MARKETING", "SALES_B2B", "CUSTOMER_SUPPORT"},
    "DIGITAL_MARKETING": {"MARKETING", "IT_SOFTWARE", "DATA_BI"},
    "SALES_B2B": {"MARKETING", "CUSTOMER_SUPPORT", "BANKING_INSURANCE", "SALES_RETAIL"},
    "SALES_RETAIL": {"CUSTOMER_SUPPORT", "LOGISTICS_WAREHOUSE", "SALES_B2B"},
    "CUSTOMER_SUPPORT": {"SALES_RETAIL", "SALES_B2B", "ADMINISTRATIVE", "HOSPITALITY"},
    "ADMINISTRATIVE": {"CUSTOMER_SUPPORT", "HR_RECRUITMENT", "FINANCE_ACCOUNTING"},
    "PROCUREMENT_PURCHASING": {"SUPPLY_CHAIN", "FINANCE_ACCOUNTING", "SALES_B2B"},
    "SUPPLY_CHAIN": {"LOGISTICS_WAREHOUSE", "PROCUREMENT_PURCHASING", "PRODUCTION_MANUFACTURING", "DATA_BI"},
    "LOGISTICS_WAREHOUSE": {"TRANSPORTATION", "SUPPLY_CHAIN", "SALES_RETAIL", "PRODUCTION_MANUFACTURING"},
    "TRANSPORTATION": {"LOGISTICS_WAREHOUSE", "CUSTOMER_SUPPORT"},
    "PRODUCTION_MANUFACTURING": {"MAINTENANCE_TECHNICAL", "LOGISTICS_WAREHOUSE", "MECHANICAL_ENGINEERING"},
    "MAINTENANCE_TECHNICAL": {"PRODUCTION_MANUFACTURING", "ELECTRICAL_ENGINEERING", "MECHANICAL_ENGINEERING", "AUTOMOTIVE_SERVICE"},
    "MECHANICAL_ENGINEERING": {"PRODUCTION_MANUFACTURING", "MAINTENANCE_TECHNICAL", "AUTOMOTIVE_SERVICE"},
    "AUTOMOTIVE_SERVICE": {"MAINTENANCE_TECHNICAL", "MECHANICAL_ENGINEERING", "TRANSPORTATION"},
    "ELECTRICAL_ENGINEERING": {"MAINTENANCE_TECHNICAL", "CONSTRUCTION", "PRODUCTION_MANUFACTURING"},
    "CONSTRUCTION": {"ELECTRICAL_ENGINEERING", "MAINTENANCE_TECHNICAL"},
    "HOSPITALITY": {"FOOD_SERVICE", "CUSTOMER_SUPPORT", "ADMINISTRATIVE"},
    "FOOD_SERVICE": {"HOSPITALITY", "CUSTOMER_SUPPORT"},
    "HEALTHCARE": {"ADMINISTRATIVE", "CUSTOMER_SUPPORT"},
    "EDUCATION": {"HR_RECRUITMENT", "CUSTOMER_SUPPORT"},
    "MANAGEMENT_LEADERSHIP": {"HR_RECRUITMENT", "SALES_B2B", "PRODUCTION_MANUFACTURING", "SUPPLY_CHAIN"},
}

# Familii unde cerintele tehnice/profesionale sunt eliminatorii.
STRICT_FAMILIES = {
    "IT_SOFTWARE", "IT_INFRASTRUCTURE", "DATA_BI", "CYBERSECURITY",
    "FINANCE_ACCOUNTING", "LEGAL", "HEALTHCARE", "AUTOMOTIVE_SERVICE",
    "ELECTRICAL_ENGINEERING", "MECHANICAL_ENGINEERING", "CONSTRUCTION",
}

# Aliases pentru compatibilitate cu job_classifier.py
JOB_FAMILIES = JOB_TAXONOMY
ADJACENT_FAMILIES = RELATED_FAMILIES
