"""schema_initial

Revision ID: bc44b021d1f9
Revises: 
Create Date: 2026-06-01 19:19:35.039221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc44b021d1f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_events_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_events_id'), ['id'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('companies', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('cv_file', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('visible_in_dashboard', sa.Integer(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('missing_requirements', sa.Text(), nullable=True),
    sa.Column('must_verify_by_phone', sa.Text(), nullable=True),
    sa.Column('recommended_next_action', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('manager_summary', sa.Text(), nullable=True),
    sa.Column('phone_call_script', sa.Text(), nullable=True),
    sa.Column('interview_questions', sa.Text(), nullable=True),
    sa.Column('better_role_match', sa.String(), nullable=True),
    sa.Column('reject_reason_internal', sa.Text(), nullable=True),
    sa.Column('candidate_cluster', sa.String(), nullable=True),
    sa.Column('job_cluster', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_id'), ['id'], unique=False)

    op.create_table('cv_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv_file', sa.String(), nullable=False),
    sa.Column('job_title_normalized', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cv_file', 'job_title_normalized', name='uq_cv_job')
    )
    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_analyses_cv_file'), ['cv_file'], unique=False)
        batch_op.create_index(batch_op.f('ix_cv_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cv_analyses_job_title_normalized'), ['job_title_normalized'], unique=False)

    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(), nullable=True),
    sa.Column('candidate_email', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('ora', sa.String(), nullable=False),
    sa.Column('locatie', sa.String(), nullable=True),
    sa.Column('durata', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('action_token', sa.String(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_action_token'), ['action_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_interviews_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interviews_id'), ['id'], unique=False)

    op.create_table('job_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titlu', sa.String(), nullable=False),
    sa.Column('departament', sa.String(), nullable=True),
    sa.Column('locatie', sa.String(), nullable=True),
    sa.Column('tip_contract', sa.String(), nullable=True),
    sa.Column('descriere', sa.Text(), nullable=True),
    sa.Column('responsabilitati', sa.Text(), nullable=True),
    sa.Column('cerinte', sa.Text(), nullable=True),
    sa.Column('ce_oferim', sa.Text(), nullable=True),
    sa.Column('activ', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_posts_id'), ['id'], unique=False)

    op.create_table('scheduling_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduling_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduling_tokens_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduling_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduling_tokens_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduling_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduling_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_scheduling_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_scheduling_tokens_candidate_id'))

    op.drop_table('scheduling_tokens')
    with op.batch_alter_table('job_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_posts_id'))

    op.drop_table('job_posts')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_id'))
        batch_op.drop_index(batch_op.f('ix_interviews_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_interviews_action_token'))

    op.drop_table('interviews')
    with op.batch_alter_table('cv_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cv_analyses_job_title_normalized'))
        batch_op.drop_index(batch_op.f('ix_cv_analyses_id'))
        batch_op.drop_index(batch_op.f('ix_cv_analyses_cv_file'))

    op.drop_table('cv_analyses')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_id'))

    op.drop_table('candidates')
    with op.batch_alter_table('candidate_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_events_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_events_candidate_id'))

    op.drop_table('candidate_events')
    # ### end Alembic commands ###
